name: Build and Deploy Dev

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build-and-deploy:
    name: Build and Deploy Dev Image
    runs-on: [self-hosted, dev]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Load Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          # push: false # Не пушим в registry
          load: true   # Загружаем в локальный Docker daemon
          tags: spy-dev-image:latest # Тег для локального образа

      # --- ДОБАВЛЕН ШАГ ДЕПЛОЯ ---
      - name: Deploy using Docker Compose on L2
        run: |
          echo "Deploying spy-dev service..."
          # Переходим в директорию с основным docker-compose.yml
          cd ~/monitoring
          # Запускаем или обновляем ТОЛЬКО сервис spy-dev
          docker compose up -d --force-recreate spy-dev
          echo "Deployment complete."
      # --- КОНЕЦ ШАГА ДЕПЛОЯ ---