name: Deploy to Dev

on:
  push:
    branches: [ dev ] # Запускать при пуше в ветку dev

jobs:
  build-and-deploy:
    runs-on: [self-hosted, dev] # <-- Указываем метки раннера
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # --- Дальнейшие шаги: ---
      # - name: Setup Node.js (пример)
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: '18'

      # - name: Install dependencies
      #   run: npm ci

      # - name: Run Linter
      #   run: npm run lint

      # - name: Run Tests
      #   run: npm test

      # - name: Build project
      #   run: npm run build

      # - name: Deploy static files to L2 (пример)
      #   run: |
      #     sudo rm -rf /data/main/www/spy/*
      #     sudo cp -r ./dist/* /data/main/www/spy/
      #     sudo chown -R 1000:1000 /data/main/www/spy # Установить права, если нужно веб-серверу

      # --- Или шаги для Docker ---
      # - name: Login to Local Docker Registry
      #   uses: docker/login-action@v2
      #   with:
      #     registry: localhost:5000
      #     username: ${{ secrets.DOCKER_USERNAME }} # Если настроил аутентификацию
      #     password: ${{ secrets.DOCKER_PASSWORD }} # Если настроил аутентификацию

      # - name: Build and Push Docker image
      #   uses: docker/build-push-action@v4
      #   with:
      #     context: .
      #     push: true
      #     tags: localhost:5000/spy-dev:latest

      # - name: Deploy using Docker Compose on L2
      #   run: |
      #     cd /путь/к/compose/файлу/на/L2 # Возможно, нужно указать путь
      #     docker compose pull spy-dev
      #     docker compose up -d --force-recreate spy-dev